FROM mirror.gcr.io/alpine:3

# hadolint ignore=DL3018
RUN apk add --no-cache \
        bash \
        git \
        openssh \
        tar \
        gzip \
        curl \
        jq \
        ca-certificates
