FROM mirror.gcr.io/ubuntu:24.04

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git \
            openssh-server \
            tar \
            gzip \
            ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
