FROM alpine

LABEL org.opencontainers.image.created="%%CREATED%%" \
      org.opencontainers.image.authors="nic.cheneweth@thoughtworks.com" \
      org.opencontainers.image.url="https://github.com/ThoughtWorks-DPS/orb-executor-tools" \
      org.opencontainers.image.documentation="https://github.com/ThoughtWorks-DPS/orb-executor-tools" \
      org.opencontainers.image.source="https://github.com/ThoughtWorks-DPS/orb-executor-tools" \
      org.opencontainers.image.version="%%VERSION%%" \
      org.opencontainers.image.vendor="ThoughtWorks, Inc." \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.title="orb-executor-tools" \
      org.opencontainers.image.description="Build artifact for orb-executor-tools integration testing" \
      org.opencontainers.image.base.name="%%BASE%%"

# hadolint ignore=DL3018,DL3006
RUN apk add --no-cache \
        git \
        openssh \
        sudo \
        tar \
        gzip \
        ca-certificates
